server:
  port: 18085

app:
  reservation:
    timeout-minutes: 10
    cleanup-interval-ms: 300000

spring:
  config:
    import: "common-config.yml"
  datasource:
    url: jdbc:postgresql://localhost:15439/inventory_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver    
