spring:
  profiles:
    active: "default"

stripe:
  api:
    secret-key: sk_test_51SE48THRWMzXfAFedGPQ02RwkGnexkJXFeFi6ckainh6NN2dEcGt1if7C8ZqHeRBTbiUmJCaPBibr6nQsgLp5ena00X7YwcW11
    client-id: ca_TAak0BWyIkV04HPOSCWKapGXV2D3VEPU

seller:
  service:
    url: http://localhost:8082

onboarding:
  redirect-uri: "http://localhost:8081/api/onboarding/oauth/callback"

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
